Handle SVN peg paths during release preparation (#36)

diff --git a/tests/release/fakes/svn b/tests/release/fakes/svn
--- a/tests/release/fakes/svn
+++ b/tests/release/fakes/svn
@@ -113,6 +113,12 @@ case $command in
     ;;
   rm)
     test "$#" -eq 2 && test "$1" = --force || { printf 'fake svn: unsupported rm arguments\n' >&2; exit 64; }
+    if test "${FAKE_SVN_MODE:-}" = require-peg-escape; then
+      test "$2" = "${FAKE_SVN_MISSING_PATH:?}@" || {
+        printf 'fake svn: missing trailing peg escape\n' >&2
+        exit 65
+      }
+    fi
     case $(normalize "$2") in trunk/*) ;; *) printf 'fake svn: rm target must be under trunk\n' >&2; exit 64 ;; esac
     ;;
   copy)
